// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions {
	class ACE {
		class Spectator {
			// ACE_fnc_startSpectator
			class startSpectator {
				description = "Start spectator script";
				file = "\x\ace\Addons\sys_spectator\fnc_startSpectator.sqf";
			};
		};
	};
};
